//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AggregatedIndependentAmount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggregatedIndependentAmount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="trade" type="{http://www.fpml.org/FpML-5/master}IndependentAmountType"/>
 *         &lt;element name="valueAtRisk" type="{http://www.fpml.org/FpML-5/master}IndependentAmountType"/>
 *         &lt;element name="netOpenPosition" type="{http://www.fpml.org/FpML-5/master}IndependentAmountType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregatedIndependentAmount", propOrder = {
    "tradeOrValueAtRiskOrNetOpenPosition"
})
public class AggregatedIndependentAmount {

    @XmlElementRefs({
        @XmlElementRef(name = "valueAtRisk", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "trade", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "netOpenPosition", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<IndependentAmountType>> tradeOrValueAtRiskOrNetOpenPosition;

    /**
     * Gets the value of the tradeOrValueAtRiskOrNetOpenPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tradeOrValueAtRiskOrNetOpenPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTradeOrValueAtRiskOrNetOpenPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IndependentAmountType }{@code >}
     * {@link JAXBElement }{@code <}{@link IndependentAmountType }{@code >}
     * {@link JAXBElement }{@code <}{@link IndependentAmountType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<IndependentAmountType>> getTradeOrValueAtRiskOrNetOpenPosition() {
        if (tradeOrValueAtRiskOrNetOpenPosition == null) {
            tradeOrValueAtRiskOrNetOpenPosition = new ArrayList<JAXBElement<IndependentAmountType>>();
        }
        return this.tradeOrValueAtRiskOrNetOpenPosition;
    }

}
