//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BreakageCalculatedByEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BreakageCalculatedByEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Agent Bank"/>
 *     &lt;enumeration value="Lender"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BreakageCalculatedByEnum")
@XmlEnum
public enum BreakageCalculatedByEnum {


    /**
     * Breakage cost is calculated by the agent bank.
     * 
     */
    @XmlEnumValue("Agent Bank")
    AGENT_BANK("Agent Bank"),

    /**
     * Breakage cost is calculated by the lender.
     * 
     */
    @XmlEnumValue("Lender")
    LENDER("Lender");
    private final String value;

    BreakageCalculatedByEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BreakageCalculatedByEnum fromValue(String v) {
        for (BreakageCalculatedByEnum c: BreakageCalculatedByEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
