//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A type definining the parameters used in the calculation of fixed or floating calculation period amounts.
 * 
 * <p>Java class for Calculation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Calculation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="notionalSchedule" type="{http://www.fpml.org/FpML-5/master}Notional"/>
 *           &lt;element name="fxLinkedNotionalSchedule" type="{http://www.fpml.org/FpML-5/master}FxLinkedNotionalSchedule"/>
 *           &lt;sequence>
 *             &lt;element name="currentNotional" type="{http://www.fpml.org/FpML-5/master}Money"/>
 *             &lt;element name="notionalSchedule" type="{http://www.fpml.org/FpML-5/master}Notional" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="fixedRateSchedule" type="{http://www.fpml.org/FpML-5/master}Schedule" minOccurs="0"/>
 *             &lt;element name="futureValueNotional" type="{http://www.fpml.org/FpML-5/master}FutureValueAmount" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://www.fpml.org/FpML-5/master}rateCalculation"/>
 *         &lt;/choice>
 *         &lt;element name="dayCountFraction" type="{http://www.fpml.org/FpML-5/master}DayCountFraction" minOccurs="0"/>
 *         &lt;element name="discounting" type="{http://www.fpml.org/FpML-5/master}Discounting" minOccurs="0"/>
 *         &lt;element name="compoundingMethod" type="{http://www.fpml.org/FpML-5/master}CompoundingMethodEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Calculation", propOrder = {
    "content"
})
public class Calculation {

    @XmlElementRefs({
        @XmlElementRef(name = "fxLinkedNotionalSchedule", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dayCountFraction", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "discounting", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "currentNotional", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "notionalSchedule", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fixedRateSchedule", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "futureValueNotional", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rateCalculation", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "compoundingMethod", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "NotionalSchedule" is used by two different parts of a schema. See: 
     * line 120 of file:/C:/DEV/git/integrella/integrella-microservices-producer-fpml/src/main/xsd/schema/fpml-ird.xsd
     * line 82 of file:/C:/DEV/git/integrella/integrella-microservices-producer-fpml/src/main/xsd/schema/fpml-ird.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link FxLinkedNotionalSchedule }{@code >}
     * {@link JAXBElement }{@code <}{@link DayCountFraction }{@code >}
     * {@link JAXBElement }{@code <}{@link InflationRateCalculation }{@code >}
     * {@link JAXBElement }{@code <}{@link Discounting }{@code >}
     * {@link JAXBElement }{@code <}{@link Money }{@code >}
     * {@link JAXBElement }{@code <}{@link Notional }{@code >}
     * {@link JAXBElement }{@code <}{@link FloatingRateCalculation }{@code >}
     * {@link JAXBElement }{@code <}{@link Schedule }{@code >}
     * {@link JAXBElement }{@code <}{@link FutureValueAmount }{@code >}
     * {@link JAXBElement }{@code <}{@link Rate }{@code >}
     * {@link JAXBElement }{@code <}{@link CompoundingMethodEnum }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
