//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type defining an interest rate cap, floor, or cap/floor strategy (e.g. collar) product.
 * 
 * <p>Java class for CapFloor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapFloor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}Product">
 *       &lt;sequence>
 *         &lt;element name="capFloorStream" type="{http://www.fpml.org/FpML-5/master}InterestRateStream" minOccurs="0"/>
 *         &lt;element name="premium" type="{http://www.fpml.org/FpML-5/master}Payment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="additionalPayment" type="{http://www.fpml.org/FpML-5/master}Payment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="earlyTerminationProvision" type="{http://www.fpml.org/FpML-5/master}EarlyTerminationProvision" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapFloor")
public class CapFloor
    extends Product
{


}
