//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The physical delivery conditions for coal.
 * 
 * <p>Java class for CoalDelivery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoalDelivery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="deliveryPoint" type="{http://www.fpml.org/FpML-5/master}CoalDeliveryPoint"/>
 *           &lt;element name="deliveryAtSource" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;/choice>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}CommodityUSCoalDelivery.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoalDelivery", propOrder = {
    "deliveryPoint",
    "deliveryAtSource",
    "quantityVariationAdjustment",
    "transportationEquipment",
    "risk"
})
public class CoalDelivery {

    protected CoalDeliveryPoint deliveryPoint;
    protected Boolean deliveryAtSource;
    protected Boolean quantityVariationAdjustment;
    protected CoalTransportationEquipment transportationEquipment;
    protected CommodityDeliveryRisk risk;

    /**
     * Gets the value of the deliveryPoint property.
     * 
     * @return
     *     possible object is
     *     {@link CoalDeliveryPoint }
     *     
     */
    public CoalDeliveryPoint getDeliveryPoint() {
        return deliveryPoint;
    }

    /**
     * Sets the value of the deliveryPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalDeliveryPoint }
     *     
     */
    public void setDeliveryPoint(CoalDeliveryPoint value) {
        this.deliveryPoint = value;
    }

    /**
     * Gets the value of the deliveryAtSource property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeliveryAtSource() {
        return deliveryAtSource;
    }

    /**
     * Sets the value of the deliveryAtSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeliveryAtSource(Boolean value) {
        this.deliveryAtSource = value;
    }

    /**
     * Gets the value of the quantityVariationAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isQuantityVariationAdjustment() {
        return quantityVariationAdjustment;
    }

    /**
     * Sets the value of the quantityVariationAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQuantityVariationAdjustment(Boolean value) {
        this.quantityVariationAdjustment = value;
    }

    /**
     * Gets the value of the transportationEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link CoalTransportationEquipment }
     *     
     */
    public CoalTransportationEquipment getTransportationEquipment() {
        return transportationEquipment;
    }

    /**
     * Sets the value of the transportationEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalTransportationEquipment }
     *     
     */
    public void setTransportationEquipment(CoalTransportationEquipment value) {
        this.transportationEquipment = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityDeliveryRisk }
     *     
     */
    public CommodityDeliveryRisk getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityDeliveryRisk }
     *     
     */
    public void setRisk(CommodityDeliveryRisk value) {
        this.risk = value;
    }

}
