//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Commodity Forward
 * 
 * <p>Java class for CommodityForward complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityForward">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}Product">
 *       &lt;sequence>
 *         &lt;element name="valueDate" type="{http://www.fpml.org/FpML-5/master}AdjustableOrRelativeDate" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="fixedLeg" type="{http://www.fpml.org/FpML-5/master}NonPeriodicFixedPriceLeg"/>
 *           &lt;element name="averagePriceLeg" type="{http://www.fpml.org/FpML-5/master}AveragePriceLeg"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.fpml.org/FpML-5/master}commodityForwardLeg" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}CommodityContent.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityForward")
public class CommodityForward
    extends Product
{


}
