//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the digital commodity option product type. Digital options exercise when a barrier is breached and are financially settled. The 'commodityDigitalOption' type is an extension of the 'commodityOption' product.
 * 
 * <p>Java class for CommodityDigitalOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityDigitalOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}Option">
 *       &lt;sequence>
 *         &lt;element name="optionType" type="{http://www.fpml.org/FpML-5/master}PutCallEnum" minOccurs="0"/>
 *         &lt;element name="commodity" type="{http://www.fpml.org/FpML-5/master}Commodity" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}CommodityDigitalOptionFeatures.model"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="notionalAmount" type="{http://www.fpml.org/FpML-5/master}NotionalAmount"/>
 *           &lt;sequence>
 *             &lt;element name="notionalQuantity" type="{http://www.fpml.org/FpML-5/master}CommodityNotionalQuantity" minOccurs="0"/>
 *             &lt;element name="totalNotionalQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="exercise" type="{http://www.fpml.org/FpML-5/master}CommodityDigitalExercise" minOccurs="0"/>
 *         &lt;element name="premium" type="{http://www.fpml.org/FpML-5/master}CommodityPremium" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}CommodityContent.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityDigitalOption")
public class CommodityDigitalOption
    extends Option
{


}
