//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A set of default probabilities.
 * 
 * <p>Java class for DefaultProbabilityCurve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefaultProbabilityCurve">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}PricingStructureValuation">
 *       &lt;sequence>
 *         &lt;element name="baseYieldCurve" type="{http://www.fpml.org/FpML-5/master}PricingStructureReference" minOccurs="0"/>
 *         &lt;element name="defaultProbabilities" type="{http://www.fpml.org/FpML-5/master}TermCurve" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultProbabilityCurve", propOrder = {
    "baseYieldCurve",
    "defaultProbabilities"
})
public class DefaultProbabilityCurve
    extends PricingStructureValuation
{

    protected PricingStructureReference baseYieldCurve;
    protected TermCurve defaultProbabilities;

    /**
     * Gets the value of the baseYieldCurve property.
     * 
     * @return
     *     possible object is
     *     {@link PricingStructureReference }
     *     
     */
    public PricingStructureReference getBaseYieldCurve() {
        return baseYieldCurve;
    }

    /**
     * Sets the value of the baseYieldCurve property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingStructureReference }
     *     
     */
    public void setBaseYieldCurve(PricingStructureReference value) {
        this.baseYieldCurve = value;
    }

    /**
     * Gets the value of the defaultProbabilities property.
     * 
     * @return
     *     possible object is
     *     {@link TermCurve }
     *     
     */
    public TermCurve getDefaultProbabilities() {
        return defaultProbabilities;
    }

    /**
     * Sets the value of the defaultProbabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermCurve }
     *     
     */
    public void setDefaultProbabilities(TermCurve value) {
        this.defaultProbabilities = value;
    }

}
