//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents an evergreen option that is available within a letter of credit instrument.
 * 
 * <p>Java class for EvergreenOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvergreenOption">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nonRenewalNoticePeriod" type="{http://www.fpml.org/FpML-5/master}Period" minOccurs="0"/>
 *         &lt;element name="extensionPeriod" type="{http://www.fpml.org/FpML-5/master}Period" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvergreenOption", propOrder = {
    "nonRenewalNoticePeriod",
    "extensionPeriod"
})
public class EvergreenOption {

    protected Period nonRenewalNoticePeriod;
    protected Period extensionPeriod;

    /**
     * Gets the value of the nonRenewalNoticePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getNonRenewalNoticePeriod() {
        return nonRenewalNoticePeriod;
    }

    /**
     * Sets the value of the nonRenewalNoticePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setNonRenewalNoticePeriod(Period value) {
        this.nonRenewalNoticePeriod = value;
    }

    /**
     * Gets the value of the extensionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getExtensionPeriod() {
        return extensionPeriod;
    }

    /**
     * Sets the value of the extensionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setExtensionPeriod(Period value) {
        this.extensionPeriod = value;
    }

}
