//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents current/prior facility commitment and outstanding amounts on both the global and lender position levels.
 * 
 * <p>Java class for FacilityOutstandingsPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityOutstandingsPosition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}FacilityPosition">
 *       &lt;sequence>
 *         &lt;element name="outstandingsPosition" type="{http://www.fpml.org/FpML-5/master}OutstandingsPosition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityOutstandingsPosition", propOrder = {
    "outstandingsPosition"
})
public class FacilityOutstandingsPosition
    extends FacilityPosition
{

    protected List<OutstandingsPosition> outstandingsPosition;

    /**
     * Gets the value of the outstandingsPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outstandingsPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutstandingsPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutstandingsPosition }
     * 
     * 
     */
    public List<OutstandingsPosition> getOutstandingsPosition() {
        if (outstandingsPosition == null) {
            outstandingsPosition = new ArrayList<OutstandingsPosition>();
        }
        return this.outstandingsPosition;
    }

}
