//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the abstract type underlying a fixed rate cash accrual option.
 * 
 * <p>Java class for FixedRateOptionBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FixedRateOptionBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}AccrualOptionBase">
 *       &lt;sequence>
 *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pikSpread" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FixedRateOptionBase", propOrder = {
    "rate",
    "pikSpread"
})
@XmlSeeAlso({
    FixedRateOption.class,
    FixedRateAccrual.class
})
public abstract class FixedRateOptionBase
    extends AccrualOptionBase
{

    protected BigDecimal rate;
    @XmlElement(defaultValue = "xsd:decimal")
    protected Object pikSpread;

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the pikSpread property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPikSpread() {
        return pikSpread;
    }

    /**
     * Sets the value of the pikSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPikSpread(Object value) {
        this.pikSpread = value;
    }

}
