//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FxAccrualRegionLowerBound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FxAccrualRegionLowerBound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.fpml.org/FpML-5/master}FxRegionLowerBoundDirectionEnum" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}FxAccrualConditionLevel.model"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FxAccrualRegionLowerBound", propOrder = {
    "condition",
    "level",
    "quoteBasis",
    "strikeReference",
    "averageStrikeReference",
    "triggerReference"
})
public class FxAccrualRegionLowerBound {

    protected FxRegionLowerBoundDirectionEnum condition;
    protected FxLevel level;
    protected QuoteBasisEnum quoteBasis;
    protected FxAccrualStrikeReference strikeReference;
    protected FxAccrualAverageStrikeReference averageStrikeReference;
    protected FxAccrualTriggerReference triggerReference;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link FxRegionLowerBoundDirectionEnum }
     *     
     */
    public FxRegionLowerBoundDirectionEnum getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxRegionLowerBoundDirectionEnum }
     *     
     */
    public void setCondition(FxRegionLowerBoundDirectionEnum value) {
        this.condition = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link FxLevel }
     *     
     */
    public FxLevel getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxLevel }
     *     
     */
    public void setLevel(FxLevel value) {
        this.level = value;
    }

    /**
     * Gets the value of the quoteBasis property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteBasisEnum }
     *     
     */
    public QuoteBasisEnum getQuoteBasis() {
        return quoteBasis;
    }

    /**
     * Sets the value of the quoteBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteBasisEnum }
     *     
     */
    public void setQuoteBasis(QuoteBasisEnum value) {
        this.quoteBasis = value;
    }

    /**
     * Gets the value of the strikeReference property.
     * 
     * @return
     *     possible object is
     *     {@link FxAccrualStrikeReference }
     *     
     */
    public FxAccrualStrikeReference getStrikeReference() {
        return strikeReference;
    }

    /**
     * Sets the value of the strikeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAccrualStrikeReference }
     *     
     */
    public void setStrikeReference(FxAccrualStrikeReference value) {
        this.strikeReference = value;
    }

    /**
     * Gets the value of the averageStrikeReference property.
     * 
     * @return
     *     possible object is
     *     {@link FxAccrualAverageStrikeReference }
     *     
     */
    public FxAccrualAverageStrikeReference getAverageStrikeReference() {
        return averageStrikeReference;
    }

    /**
     * Sets the value of the averageStrikeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAccrualAverageStrikeReference }
     *     
     */
    public void setAverageStrikeReference(FxAccrualAverageStrikeReference value) {
        this.averageStrikeReference = value;
    }

    /**
     * Gets the value of the triggerReference property.
     * 
     * @return
     *     possible object is
     *     {@link FxAccrualTriggerReference }
     *     
     */
    public FxAccrualTriggerReference getTriggerReference() {
        return triggerReference;
    }

    /**
     * Sets the value of the triggerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAccrualTriggerReference }
     *     
     */
    public void setTriggerReference(FxAccrualTriggerReference value) {
        this.triggerReference = value;
    }

}
