//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FxAccrualBarrier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FxAccrualBarrier">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}FxComplexBarrierBase">
 *       &lt;sequence>
 *         &lt;element name="accrualRetention" type="{http://www.fpml.org/FpML-5/master}FxAccrualKnockoutBarrierRetentionEnum" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="observableReference" type="{http://www.fpml.org/FpML-5/master}FxRateObservableReference"/>
 *           &lt;sequence>
 *             &lt;element name="quotedCurrencyPair" type="{http://www.fpml.org/FpML-5/master}QuotedCurrencyPair" minOccurs="0"/>
 *             &lt;element name="informationSource" type="{http://www.fpml.org/FpML-5/master}InformationSource" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FxAccrualBarrier", propOrder = {
    "accrualRetention",
    "observableReference",
    "quotedCurrencyPair",
    "informationSource"
})
public class FxAccrualBarrier
    extends FxComplexBarrierBase
{

    protected FxAccrualKnockoutBarrierRetentionEnum accrualRetention;
    protected FxRateObservableReference observableReference;
    protected QuotedCurrencyPair quotedCurrencyPair;
    protected List<InformationSource> informationSource;

    /**
     * Gets the value of the accrualRetention property.
     * 
     * @return
     *     possible object is
     *     {@link FxAccrualKnockoutBarrierRetentionEnum }
     *     
     */
    public FxAccrualKnockoutBarrierRetentionEnum getAccrualRetention() {
        return accrualRetention;
    }

    /**
     * Sets the value of the accrualRetention property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAccrualKnockoutBarrierRetentionEnum }
     *     
     */
    public void setAccrualRetention(FxAccrualKnockoutBarrierRetentionEnum value) {
        this.accrualRetention = value;
    }

    /**
     * Gets the value of the observableReference property.
     * 
     * @return
     *     possible object is
     *     {@link FxRateObservableReference }
     *     
     */
    public FxRateObservableReference getObservableReference() {
        return observableReference;
    }

    /**
     * Sets the value of the observableReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxRateObservableReference }
     *     
     */
    public void setObservableReference(FxRateObservableReference value) {
        this.observableReference = value;
    }

    /**
     * Gets the value of the quotedCurrencyPair property.
     * 
     * @return
     *     possible object is
     *     {@link QuotedCurrencyPair }
     *     
     */
    public QuotedCurrencyPair getQuotedCurrencyPair() {
        return quotedCurrencyPair;
    }

    /**
     * Sets the value of the quotedCurrencyPair property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuotedCurrencyPair }
     *     
     */
    public void setQuotedCurrencyPair(QuotedCurrencyPair value) {
        this.quotedCurrencyPair = value;
    }

    /**
     * Gets the value of the informationSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informationSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformationSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InformationSource }
     * 
     * 
     */
    public List<InformationSource> getInformationSource() {
        if (informationSource == null) {
            informationSource = new ArrayList<InformationSource>();
        }
        return this.informationSource;
    }

}
