//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FxBarrierDirectionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FxBarrierDirectionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Down"/>
 *     &lt;enumeration value="Up"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FxBarrierDirectionEnum")
@XmlEnum
public enum FxBarrierDirectionEnum {


    /**
     * The barrier is triggered if the observed rate is at or below the barrier level during the period of observation, or at the time of observation.
     * 
     */
    @XmlEnumValue("Down")
    DOWN("Down"),

    /**
     * The barrier is triggered if the observed rate is at or above the barrier level during the period of observation, or at the time of observation.
     * 
     */
    @XmlEnumValue("Up")
    UP("Up");
    private final String value;

    FxBarrierDirectionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FxBarrierDirectionEnum fromValue(String v) {
        for (FxBarrierDirectionEnum c: FxBarrierDirectionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
