//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FxSettlementAdjustmentMethodEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FxSettlementAdjustmentMethodEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="VariedStrike"/>
 *     &lt;enumeration value="VariedNotional"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FxSettlementAdjustmentMethodEnum")
@XmlEnum
public enum FxSettlementAdjustmentMethodEnum {

    @XmlEnumValue("VariedStrike")
    VARIED_STRIKE("VariedStrike"),
    @XmlEnumValue("VariedNotional")
    VARIED_NOTIONAL("VariedNotional");
    private final String value;

    FxSettlementAdjustmentMethodEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FxSettlementAdjustmentMethodEnum fromValue(String v) {
        for (FxSettlementAdjustmentMethodEnum c: FxSettlementAdjustmentMethodEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
