//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Simple product representation providing key information about a variety of different products. Generic products - for use in Transparency reporting to define a product that represents an OTC derivative transaction whose economics are not fully described using an FpML schema. In other views, generic products are present for convenience to support internal messaging and workflows that are cross-product. Generic products are not full trade representations as such they are not intended to be used for confirming trades.
 * 
 * <p>Java class for GenericProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericProduct">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}Product">
 *       &lt;sequence>
 *         &lt;element name="multiLeg" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;group ref="{http://www.fpml.org/FpML-5/master}BuyerSeller.model"/>
 *           &lt;element name="counterpartyReference" type="{http://www.fpml.org/FpML-5/master}PartyReference" maxOccurs="2" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="premium" type="{http://www.fpml.org/FpML-5/master}SimplePayment" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.fpml.org/FpML-5/master}AdjustableDate2" minOccurs="0"/>
 *         &lt;element name="expirationDate" type="{http://www.fpml.org/FpML-5/master}AdjustableDate2" minOccurs="0"/>
 *         &lt;element name="terminationDate" type="{http://www.fpml.org/FpML-5/master}AdjustableDate2" minOccurs="0"/>
 *         &lt;element name="underlyer" type="{http://www.fpml.org/FpML-5/master}TradeUnderlyer2" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="notional" type="{http://www.fpml.org/FpML-5/master}CashflowNotional" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}GenericCommodityAttributes.model" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}GenericEquityAttributes.model" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}GenericOptionAttributes.model" minOccurs="0"/>
 *         &lt;element name="paymentFrequency" type="{http://www.fpml.org/FpML-5/master}GenericFrequency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resetFrequency" type="{http://www.fpml.org/FpML-5/master}GenericResetFrequency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="settlementCurrency" type="{http://www.fpml.org/FpML-5/master}IdentifiedCurrency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="settlementType" type="{http://www.fpml.org/FpML-5/master}SettlementTypeEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericProduct")
public class GenericProduct
    extends Product
{


}
