//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterestPaymentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterestPaymentDetails">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}NonNegativePayment">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.fpml.org/FpML-5/master}InterestMethodEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterestPaymentDetails", propOrder = {
    "method"
})
public class InterestPaymentDetails
    extends NonNegativePayment
{

    protected InterestMethodEnum method;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link InterestMethodEnum }
     *     
     */
    public InterestMethodEnum getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestMethodEnum }
     *     
     */
    public void setMethod(InterestMethodEnum value) {
        this.method = value;
    }

}
