//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LcAutoAdjustEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LcAutoAdjustEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="AutoDecrease"/>
 *     &lt;enumeration value="AutoIncrease"/>
 *     &lt;enumeration value="AutoIncreaseOrDecrease"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LcAutoAdjustEnum")
@XmlEnum
public enum LcAutoAdjustEnum {


    /**
     * Denotes an automatic decrease.
     * 
     */
    @XmlEnumValue("AutoDecrease")
    AUTO_DECREASE("AutoDecrease"),

    /**
     * Denotes an automatic increase.
     * 
     */
    @XmlEnumValue("AutoIncrease")
    AUTO_INCREASE("AutoIncrease"),

    /**
     * Denotes an automatic increase or decrease.
     * 
     */
    @XmlEnumValue("AutoIncreaseOrDecrease")
    AUTO_INCREASE_OR_DECREASE("AutoIncreaseOrDecrease");
    private final String value;

    LcAutoAdjustEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LcAutoAdjustEnum fromValue(String v) {
        for (LcAutoAdjustEnum c: LcAutoAdjustEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
