//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * An abstract base type for all LC-level business events.
 * 
 * <p>Java class for LcEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LcEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}LoanEvent">
 *       &lt;sequence>
 *         &lt;element name="letterOfCreditReference" type="{http://www.fpml.org/FpML-5/master}LetterOfCreditReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LcEvent", propOrder = {
    "letterOfCreditReference"
})
@XmlSeeAlso({
    LcIssuance.class,
    LcFxRevaluation.class,
    LcAdjustment.class,
    LcRateChange.class,
    LcTermination.class,
    LcRenewal.class,
    LcIssuanceFeePayment.class
})
public abstract class LcEvent
    extends LoanEvent
{

    protected LetterOfCreditReference letterOfCreditReference;

    /**
     * Gets the value of the letterOfCreditReference property.
     * 
     * @return
     *     possible object is
     *     {@link LetterOfCreditReference }
     *     
     */
    public LetterOfCreditReference getLetterOfCreditReference() {
        return letterOfCreditReference;
    }

    /**
     * Sets the value of the letterOfCreditReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterOfCreditReference }
     *     
     */
    public void setLetterOfCreditReference(LetterOfCreditReference value) {
        this.letterOfCreditReference = value;
    }

}
