//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * An event representing a change in an L/C accrual option. In real terms - an example of this would be an L/C margin rate change.
 * 
 * <p>Java class for LcOptionChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LcOptionChange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}FacilityEvent">
 *       &lt;sequence>
 *         &lt;element name="lcOption" type="{http://www.fpml.org/FpML-5/master}LcOption" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LcOptionChange", propOrder = {
    "lcOption"
})
public class LcOptionChange
    extends FacilityEvent
{

    protected LcOption lcOption;

    /**
     * Gets the value of the lcOption property.
     * 
     * @return
     *     possible object is
     *     {@link LcOption }
     *     
     */
    public LcOption getLcOption() {
        return lcOption;
    }

    /**
     * Sets the value of the lcOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link LcOption }
     *     
     */
    public void setLcOption(LcOption value) {
        this.lcOption = value;
    }

}
