//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A limited version of the CDS type used as an underlyer to CDS options in Transparency view, to avoid requiring product type etc.
 * 
 * <p>Java class for LimitedCreditDefaultSwap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitedCreditDefaultSwap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generalTerms" type="{http://www.fpml.org/FpML-5/master}GeneralTerms" minOccurs="0"/>
 *         &lt;element name="feeLeg" type="{http://www.fpml.org/FpML-5/master}FeeLeg" minOccurs="0"/>
 *         &lt;element name="protectionTerms" type="{http://www.fpml.org/FpML-5/master}ProtectionTerms" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitedCreditDefaultSwap", propOrder = {
    "generalTerms",
    "feeLeg",
    "protectionTerms"
})
public class LimitedCreditDefaultSwap {

    protected GeneralTerms generalTerms;
    protected FeeLeg feeLeg;
    protected List<ProtectionTerms> protectionTerms;

    /**
     * Gets the value of the generalTerms property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralTerms }
     *     
     */
    public GeneralTerms getGeneralTerms() {
        return generalTerms;
    }

    /**
     * Sets the value of the generalTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralTerms }
     *     
     */
    public void setGeneralTerms(GeneralTerms value) {
        this.generalTerms = value;
    }

    /**
     * Gets the value of the feeLeg property.
     * 
     * @return
     *     possible object is
     *     {@link FeeLeg }
     *     
     */
    public FeeLeg getFeeLeg() {
        return feeLeg;
    }

    /**
     * Sets the value of the feeLeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeLeg }
     *     
     */
    public void setFeeLeg(FeeLeg value) {
        this.feeLeg = value;
    }

    /**
     * Gets the value of the protectionTerms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protectionTerms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtectionTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtectionTerms }
     * 
     * 
     */
    public List<ProtectionTerms> getProtectionTerms() {
        if (protectionTerms == null) {
            protectionTerms = new ArrayList<ProtectionTerms>();
        }
        return this.protectionTerms;
    }

}
