//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanParticipation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanParticipation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}PCDeliverableObligationCharac">
 *       &lt;sequence>
 *         &lt;element name="qualifyingParticipationSeller" type="{http://www.fpml.org/FpML-5/master}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanParticipation", propOrder = {
    "qualifyingParticipationSeller"
})
public class LoanParticipation
    extends PCDeliverableObligationCharac
{

    protected String qualifyingParticipationSeller;

    /**
     * Gets the value of the qualifyingParticipationSeller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifyingParticipationSeller() {
        return qualifyingParticipationSeller;
    }

    /**
     * Sets the value of the qualifyingParticipationSeller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifyingParticipationSeller(String value) {
        this.qualifyingParticipationSeller = value;
    }

}
