//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents outstanding loan contracts or outstanding letter of credit position. Both the global and lender position (current and prior) levels can be represented.
 * 
 * <p>Java class for OutstandingsPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutstandingsPosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="loanContractReference" type="{http://www.fpml.org/FpML-5/master}LoanContractReference"/>
 *           &lt;element name="letterOfCreditReference" type="{http://www.fpml.org/FpML-5/master}LetterOfCreditReference"/>
 *         &lt;/choice>
 *         &lt;sequence>
 *           &lt;element name="amount" type="{http://www.fpml.org/FpML-5/master}MoneyWithParticipantShare" minOccurs="0"/>
 *           &lt;element name="priorAmount" type="{http://www.fpml.org/FpML-5/master}MoneyWithParticipantShare" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="facilityFxRate" type="{http://www.fpml.org/FpML-5/master}FxTerms" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutstandingsPosition", propOrder = {
    "loanContractReference",
    "letterOfCreditReference",
    "amount",
    "priorAmount",
    "facilityFxRate"
})
public class OutstandingsPosition {

    protected LoanContractReference loanContractReference;
    protected LetterOfCreditReference letterOfCreditReference;
    protected MoneyWithParticipantShare amount;
    protected MoneyWithParticipantShare priorAmount;
    protected FxTerms facilityFxRate;

    /**
     * Gets the value of the loanContractReference property.
     * 
     * @return
     *     possible object is
     *     {@link LoanContractReference }
     *     
     */
    public LoanContractReference getLoanContractReference() {
        return loanContractReference;
    }

    /**
     * Sets the value of the loanContractReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanContractReference }
     *     
     */
    public void setLoanContractReference(LoanContractReference value) {
        this.loanContractReference = value;
    }

    /**
     * Gets the value of the letterOfCreditReference property.
     * 
     * @return
     *     possible object is
     *     {@link LetterOfCreditReference }
     *     
     */
    public LetterOfCreditReference getLetterOfCreditReference() {
        return letterOfCreditReference;
    }

    /**
     * Sets the value of the letterOfCreditReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterOfCreditReference }
     *     
     */
    public void setLetterOfCreditReference(LetterOfCreditReference value) {
        this.letterOfCreditReference = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyWithParticipantShare }
     *     
     */
    public MoneyWithParticipantShare getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyWithParticipantShare }
     *     
     */
    public void setAmount(MoneyWithParticipantShare value) {
        this.amount = value;
    }

    /**
     * Gets the value of the priorAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyWithParticipantShare }
     *     
     */
    public MoneyWithParticipantShare getPriorAmount() {
        return priorAmount;
    }

    /**
     * Sets the value of the priorAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyWithParticipantShare }
     *     
     */
    public void setPriorAmount(MoneyWithParticipantShare value) {
        this.priorAmount = value;
    }

    /**
     * Gets the value of the facilityFxRate property.
     * 
     * @return
     *     possible object is
     *     {@link FxTerms }
     *     
     */
    public FxTerms getFacilityFxRate() {
        return facilityFxRate;
    }

    /**
     * Sets the value of the facilityFxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxTerms }
     *     
     */
    public void setFacilityFxRate(FxTerms value) {
        this.facilityFxRate = value;
    }

}
