//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A list of events that have affected a position.
 * 
 * <p>Java class for PositionHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionHistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}Events.model" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionHistory", propOrder = {
    "eventsModel"
})
public class PositionHistory {

    @XmlElementRefs({
        @XmlElementRef(name = "trade", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "optionExpiry", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "amendment", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "increase", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "terminatingEvent", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "novation", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "deClear", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "change", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tradingEvent", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "additionalEvent", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "optionExercise", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originatingEvent", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "withdrawal", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "termination", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tradePackage", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> eventsModel;

    /**
     * Gets the value of the eventsModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventsModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventsModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Trade }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionExpiry }{@code >}
     * {@link JAXBElement }{@code <}{@link TradeAmendmentContent }{@code >}
     * {@link JAXBElement }{@code <}{@link TradeNotionalChange }{@code >}
     * {@link JAXBElement }{@code <}{@link TerminatingEvent }{@code >}
     * {@link JAXBElement }{@code <}{@link TradeNovationContent }{@code >}
     * {@link JAXBElement }{@code <}{@link DeClear }{@code >}
     * {@link JAXBElement }{@code <}{@link TradeChangeContent }{@code >}
     * {@link JAXBElement }{@code <}{@link TradingEventSummary }{@code >}
     * {@link JAXBElement }{@code <}{@link AdditionalEvent }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionExercise }{@code >}
     * {@link JAXBElement }{@code <}{@link OriginatingEvent }{@code >}
     * {@link JAXBElement }{@code <}{@link Withdrawal }{@code >}
     * {@link JAXBElement }{@code <}{@link TradeNotionalChange }{@code >}
     * {@link JAXBElement }{@code <}{@link TradePackage }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getEventsModel() {
        if (eventsModel == null) {
            eventsModel = new ArrayList<JAXBElement<?>>();
        }
        return this.eventsModel;
    }

}
