//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type to specify the transport currency for each of the parties to the agreement. This Transport Currency concept is specific to the 2013 version of the Standard CSA.
 * 
 * <p>Java class for TransportCurrency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportCurrency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partyReference" type="{http://www.fpml.org/FpML-5/master}PartyReference" minOccurs="0"/>
 *         &lt;element name="electedTransportCurrency" type="{http://www.fpml.org/FpML-5/master}ElectedTransportCurrency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportCurrency", propOrder = {
    "partyReference",
    "electedTransportCurrency"
})
public class TransportCurrency {

    protected PartyReference partyReference;
    protected ElectedTransportCurrency electedTransportCurrency;

    /**
     * Gets the value of the partyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getPartyReference() {
        return partyReference;
    }

    /**
     * Sets the value of the partyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setPartyReference(PartyReference value) {
        this.partyReference = value;
    }

    /**
     * Gets the value of the electedTransportCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link ElectedTransportCurrency }
     *     
     */
    public ElectedTransportCurrency getElectedTransportCurrency() {
        return electedTransportCurrency;
    }

    /**
     * Sets the value of the electedTransportCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectedTransportCurrency }
     *     
     */
    public void setElectedTransportCurrency(ElectedTransportCurrency value) {
        this.electedTransportCurrency = value;
    }

}
