//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 04:37:38 PM BST 
//


package com.integrella.fpML.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The schedule of Calculation Period First Days and Lasts Days. If there is only one First Day - Last Day pair then the First is equal to the Effective Date and the Last Day is equal to the Termination Date.
 * 
 * <p>Java class for WeatherCalculationPeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherCalculationPeriod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="calculationPeriodFirstDay" type="{http://www.fpml.org/FpML-5/master}IdentifiedDate" minOccurs="0"/>
 *         &lt;element name="calculationPeriodEndDay" type="{http://www.fpml.org/FpML-5/master}IdentifiedDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherCalculationPeriod", propOrder = {
    "calculationPeriodFirstDay",
    "calculationPeriodEndDay"
})
public class WeatherCalculationPeriod {

    protected IdentifiedDate calculationPeriodFirstDay;
    protected IdentifiedDate calculationPeriodEndDay;

    /**
     * Gets the value of the calculationPeriodFirstDay property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedDate }
     *     
     */
    public IdentifiedDate getCalculationPeriodFirstDay() {
        return calculationPeriodFirstDay;
    }

    /**
     * Sets the value of the calculationPeriodFirstDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedDate }
     *     
     */
    public void setCalculationPeriodFirstDay(IdentifiedDate value) {
        this.calculationPeriodFirstDay = value;
    }

    /**
     * Gets the value of the calculationPeriodEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedDate }
     *     
     */
    public IdentifiedDate getCalculationPeriodEndDay() {
        return calculationPeriodEndDay;
    }

    /**
     * Sets the value of the calculationPeriodEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedDate }
     *     
     */
    public void setCalculationPeriodEndDay(IdentifiedDate value) {
        this.calculationPeriodEndDay = value;
    }

}
